### ISSUE TITLE
KeyError: 'antispider7'

### ISSUE THREAD

**Issue by ghost** [Python3WebSpider/AccountPool#2]
**Describe the bug**
docker-compose up报错如下
Traceback (most recent call last):
accountpool          |   File "run.py", line 13, in <module>
accountpool          |     getattr(Scheduler(), f'run_{args.processor}')(website)
accountpool          |   File "/app/accountpool/scheduler.py", line 43, in run_generator
accountpool          |     generator = getattr(generators, GENERATOR_MAP[website])(website)
accountpool          | KeyError: 'antispider7'

**Comment by Germey** [comment]
请用 https://github.com/Python3WebSpider/AccountPool/tree/antispider7 分支
